# Generated by Django 3.1.5 on 2021-01-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_endpoint', '0002_airplanecollector_jwt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplanecollector',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
