# Generated by Django 3.1.5 on 2021-01-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_endpoint', '0003_auto_20210125_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplanecollector',
            name='jwt_token',
        ),
    ]
